
# standard C keywords
keywords = frozenset({
    'alignas', 'alignof', 'and', 'and_eq', 'asm', 'auto',
    'bitand', 'bitor', 'bool', 'break',
    'case', 'catch', 'char', 'char16_t', 'char32_t', 'class', 'compl', 'const', 'constexpr', 'const_cast', 'continue',
    'decltype', 'default', 'delete', 'do', 'double', 'dynamic_cast',
    'else', 'enum', 'explicit', 'export', 'extern',
    'false', 'final', 'float', 'for', 'friend',
    'goto',
    'if', 'inline', 'int',
    'long',
    'mutable', 'namespace',
    'new', 'noexcept', 'not', 'not_eq', 'NULL', 'nullptr',
    'operator', 'or', 'or_eq', 'override',
    'private', 'protected', 'public',
    'register', 'reinterpret_cast', 'return',
    'short', 'signed', 'sizeof', 'static', 'static_assert', 'static_cast', 'struct', 'switch',
    'template', 'this', 'thread_local', 'throw', 'true', 'try', 'typedef', 'typeid', 'typename',
    'union', 'unsigned', 'using',
    'virtual', 'void', 'volatile',
    'wchar_t', 'while',
    'xor', 'xor_eq',
    '_asm', '__asm',
    '_Builtin', '__builtin',
    '_Cdecl', '__cdecl',
    '_declspec', '__declspec',
    '_except', '_Export', '__except', '__export',
    '_Far16', '_Far32', '_Fastcall', '_finally', '__far16', '__far32', '__fastcall', '__finally',
    '_Import', '_inline', '_int8', '_int16', '_int32', '_int64', '__import', '__inline', '__int8', '__int16', '__int32', '__int64',
    '_leave', '__leave',
    '_Optlink', '__optlink',
    '_Packed', '_Pascal', '__packed', '__pascal',
    '_stdcall', '_System', '__stdcall', '__system',
    '_try', '__thread', '__try',
    '__unaligned'
})

# standard C functions
main_set = frozenset({'main', 
                      'abort', 'abs', 'atexit', 'atof', 'atoi', 'atol', 
                      'bsearch', 
                      'calloc', 
                      'div', 
                      'exit', 
                      'free',
                      'getenv',
                      'labs', 
                      'ldiv', 
                      'malloc', 'mblen', 'mbstowcs', 'mbtowc', 
                      'putenv', 
                      'qsort', 
                      'rand', 'rand_r', 'realloc', 
                      'srand', 'strtod', 'strtod32', 'strtod64', 'strtod128', 'strtof', 'strtol', 'strtold', 'strtoul', 'system', 
                      'wcstombs', 'wctomb', 
                      'acos', 'asin', 'atan', 'atan2', 'ceil', 
                      'cos', 'cosh', 
                      'erf', 'erfc', 'exp', 
                      'fabs', 'floor', 'fmod', 'frexp', 
                      'gamma', 
                      'hypot', 
                      'j0', 'j1', 'jn', 
                      'ldexp', 'log', 'log10', 
                      'modf', 
                      'nextafter', 'nextafterl', 'nexttoward', 'nexttowardl', 
                      'pow', 
                      'quantexpd32', 'quantexpd64', 'quantexpd128', 'quantized32', 'quantized64', 'quantized128', 
                      'samequantumd32', 'samequantumd64', 'samequantumd128',
                      'sin', 'sinh', 
                      'sqrt', 
                      'tan', 'tanh', 
                      'y0', 'y1', 'yn', 
                      'asctime', 'asctime_r', 
                      'clock', 'ctime', 'ctime64', 'ctime_r', 'ctime64_r', 
                      'difftime', 'difftime64',
                      'gmtime', 'gmtime64', 'gmtime_r', 'gmtime64_r', 
                      'localtime', 'localtime64', 'localtime_r', 'localtime64_r', 
                      'mktime', 'mktime64', 
                      'strftime', 'strptime4', 
                      'time', 'time64', 
                      'assert', 
                      'btowc', 
                      'fgetwc6', 'fgetws6', 'fputwc6', 'fputws6', 'fwide6', 'fwprintf6', 'fwscanf6', 
                      'getwc6', 
                      'putwc6', 
                      'ungetwc6', 
                      'catclose6', 'catgets6', 'catopen6', 'clearerr', 
                      'fclose', 'fdopen5', 'feof', 'ferror', 'fflush1', 'fgetc1', 'fgetpos1', 'fgets1', 'fileno5', 
                      'fopen', 'fprintf', 'fputc1', 'fputs1', 'fread', 'freopen', 'fscanf', 'fseek1', 'fsetpos1', 'ftell1', 'fwrite', 
                      'getc1', 'getchar1', 'gets',
                      'perror', 'printf', 'putc1', 'putchar1', 'puts',
                      'remove', 'rename', 'rewind1', 
                      'scanf', 'setbuf', 'setvbuf','snprintf', 'sprintf', 'sscanf',
                      'tmpfile', 'tmpnam', 
                      'ungetc1', 
                      'vsnprintf', 
                      'getwchar6', 
                      'mbrlen4', 'mbrtowc4', 'mbsinit4', 'mbsrtowcs4',
                      'putwchar6', 
                      'strfmon4', 'swprintf', 'swscanf', 
                      'wcrtomb4', 'wcscat', 'wcschr', 'wcscmp', 'wcscoll4', 'wcscpy', 'wcscspn', 'wcsftime', 'wcslen', 'wcsncat', 
                      'wcsncmp', 'wcsncpy', 'wcspbrk', 'wcsptime', 'wcsrchr', 'wcsrtombs4', 'wcsspn', 'wcsstr', 'wcstod', 'wcstod32', 
                      'wcstod64', 'wcstod128', 'wcstof', 'wcstok', 'wcstol', 'wcstold', 'wcstoul', 'wcsxfrm4', 'wctype4', 'wcwidth', 
                      'wmemchr', 'wmemcmp', 'wmemcpy', 'wmemmove', 'wmemset', 'wprintf6', 'wscanf6',
                      'isalnum', 'isalpha', 'isascii4', 'isblank', 'iscntrl', 'isdigit', 'isgraph', 'islower', 'isprint', 'ispunct', 
                      'isspace', 'isupper', 'toascii', 'tolower', 'toupper', 'iswalnum4', 'iswalpha4', 'iswblank4', 'iswcntrl4', 'iswctype4',
                      'iswdigit4', 'iswgraph4', 'iswlower4', 'iswprint4', 'iswpunct4', 'iswspace4', 'iswupper4', 'iswxdigit4', 'isxdigit4', 
                      'towctrans', 'towlower4', 'towupper4', 
                      'wctrans', 'localeconv', 'setlocale', 
                      'wcslocaleconv', 
                      'longjmp', 
                      'setjmp', 
                      'memchr', 'memcmp', 'memcpy', 'memmove', 'memset', 
                      'strcat', 'strchr', 'strcmp', 'strcoll', 'strcpy', 'strcspn', 'strerror', 'strlen', 'strncat', 'strncmp', 'strncpy', 'strpbrk', 
                      'strrchr', 'strspn', 'strstr', 'strtok', 'strtok_r', 'strxfrm', 
                      'nl_langinfo4',
                      'raise', 'signal', 
                      'regcomp', 'regerror', 'regexec', 'regfree', 
                      'strcasecmp', 'strncasecmp', 
                      'va_arg', 'va_copy', 'va_end', 'va_start', 'vfprintf', 'vprintf', 'vsprintf', 'vfscanf', 'vfwscanf', 'vscanf', 'vsscanf', 'vfwprintf6',
                      'vswprintf', 'vwprintf6', 'wctob', 'vswscanf', 'vwscanf'
                      })

# arguments in main function
main_args = frozenset({'argc', 'argv'})

# operators
operator_keys = frozenset({
                        '(', ')', '[', ']', '.', 
                        '+', '-', '*', '&', '/', 
                        '%', '<', '>', '^', '|', 
                        '=', ',', '?', ':' , ';',
                        '{', '}',
                        
                        '->', '++', '--', 
                        '!~', '<<', '>>', '<=', '>=', 
                        '==', '!=', '&&', '||', '+=', 
                        '-=', '*=', '/=', '%=', '&=', '^=', '|=',
                        
                        '<<=', '>>='
                        })

